name: build

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ 2.x ]

jobs:
  run:
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          operating-system: [ubuntu-18.04]
          php-versions: ['7.1', '7.2', '7.3']
      name: PHP ${{ matrix.php-versions }}

      steps:
        - uses: actions/checkout@v2

        - name: "Setup MySQL"
          run: |
            sudo service mysql start
            sudo mysql -uroot -proot -h 127.0.0.1 -e "CREATE DATABASE shieldon_unittest;"
            sudo mysql -uroot -proot -h 127.0.0.1 -e "GRANT ALL ON shieldon_unittest.* TO 'shieldon'@'localhost' IDENTIFIED BY 'taiwan';"

        - name: "Setup Redis"
          run: |
            sudo apt-get install -y redis-server
            sudo service redis-server start

        - name: "Setup PHP with Xdebug"
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}
            extensions: mbstring, pdo, pdo_mysql, intl, zip, redis, ctype, json
            coverage: xdebug

        - name: "Setup test directory"
          run: |
            sudo mkdir /home/runner/work/shieldon/shieldon/tmp
            sudo chmod 0777 /home/runner/work/shieldon/shieldon/tmp

        - name: "Install dependencies"
          run: |
            composer update --prefer-dist --no-interaction --no-suggest

        - name: "Run tests"
          run: |
            composer test
